sudo: required
services:
    - docker

before_install:
    - docker build -t vijayknu/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vijayknu/docker-react npm test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-043961598043"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acess_key: $AWS_SECRET_KEY